server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ogclass
    username: yeonjin
    password: yeonjin
  jwt:
    key: yeonjin
    time: 1800000
